sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0

install:
  - sh -c "cd update-server/ && make"

script:
  - sh -c "cd update-server/ && make test-integration"
  - sh -c "cd update-server/ && make test-unit"

