#! /bin/bash
# This script wraps the devtoolset-4 repository for CentOS-6 as an RPM-package.
# The eclipes packages are excluded for now.
#
# rpm -qa | grep devtoolset-4 | grep -v eclipse | wc -l
#  81
# cat /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo

version=0.1

pkgname=devtoolset-4-centos6-x86-64
upstream_repo=http://mirror.centos.org/centos/6/sclo/x86_64/rh/devtoolset-4/
cutdirs=5	# leave only devtoolset-4 as a directory.

pkgvers=0.1_oc$(date +"%Y%m%d")

# tmpdir=/tmp/dt-$$/
tmpdir=/tmp/dt-12567

mkdir -p $tmpdir
# ( cd $tmpdir; wget -r -nH --cut-dirs=$cutdirs -np $upstream_repo )
find $tmpdir -name index.html\*   | xargs rm -f
find $tmpdir -name \*-eclipse-\*  | xargs rm -f

rm -rf scripts; mkdir -p scripts
:> dependencies
## Must loop aphabetically sorted, so that newest version number comes last.
## We weed out older versions by using uniquename.
for pkg in $tmpdir/*/*.rpm; do
  rpm -qp --nosignature --requires $pkg  | sed -e 's@^@Requires: @'  >> dependencies
  rpm -qp --nosignature --provides $pkg  | sed -e 's@^@Provides: @'  >> dependencies
  rpm -qp --nosignature --obsoletes $pkg | sed -e 's@^@Obsoletes: @' >> dependencies
  rpm -qp --nosignature --conflicts $pkg | sed -e 's@^@Conflicts: @' >> dependencies
  uniquename=$(echo $pkg | sed -e 's@-[0-9][^-]*-[0-9][^-]*.\(x86_64\|i586\|noarch\).rpm$@.\1.rpm@')
  test "$pkg" != "$uniquename" && mv $pkg $uniquename
  base=$(basename $uniquename .rpm)
  out=scripts/$base.none
  rpm -qp --nosignature --scripts $uniquename | while read -r line; do
    case "$line" in
      "postinstall scriptlet (using /bin/sh):")
        out=scripts/$base.postinstall
        ;;
      "preuninstall scriptlet (using /bin/sh):")
        out=scripts/$base.preuninstall
        ;;
      "postuninstall program: "*)
        out=scripts/$base.postuninstall
        echo $line | sed -e 's@^postuninstall program: @@' >> $out
        out=scripts/$base.none
        ;;
      *)
        echo $line >> $out
        ;;
    esac
  done
done

cat <<EOF_SPEC1 > $pkgname.spec
# ATTENTION: DO NOT EDIT. this file is generated by $0.
# ATTENTION: It will be overwritten by the next run. 
Name:           $pkgname
Version:        $pkgvers
Release:        1
License:        GPL
BuildRoot:      %{_tmppath}/%{name}-%{version}-build
Group:          Development
Summary:        CentOS-6 devtoolset as a package.
Source:         $pkgname.tar.bz2
Source1:        $pkgname-scripts.tar.bz2


%description
Tar ball created with 
$0 VERSION $version using
upstream_repo=$upstream_repo

EOF_SPEC1
sort -u dependencies >> $pkgname.spec
cat <<EOF_SPEC2 >> $pkgname.spec

%prep
%setup -T -c

%build

%install
mkdir -p $RPM_BUILD_ROOT/opt
tar xvf %{S:0} -C $RPM_BUILD_ROOT/opt
tar xvf %{S:1} -C $RPM_BUILD_ROOT/opt
ls -la $RPM_BUILD_ROOT/opt

%clean
rm -rf "$RPM_BUILD_ROOT"

%files
%defattr(-,root,root)
/opt/*

%post
echo now we do fancy shit
ps -efww

%changelog
EOF_SPEC2


tar jcvf $pkgname-scripts.tar.bz2 scripts
# tar jcvf $pkgname.tar.bz2 -C $tmpdir .
# rm -rf $tmpdir

osc add $pkgname.tar.bz2 
osc add $pkgname-scripts.tar.bz2
osc add $pkgname.spec 

