#!/bin/bash

#================================================================================
#
#         FILE:  config
#
#        USAGE:  Source(d) by makemac.sh or makewinlin.sh
#
#  DESCRIPTION:  Config settings to be used by makemac.sh or makewinlin.sh
#
# REQUIREMENTS:  ---
#       AUTHOR:  Koen Willems
#                Sendin B.V. <info at sendin.nl>
#      VERSION:  1.0.0
#      CREATED:  August 10, 2014
#
#================================================================================

#================================================================================
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2 of the License.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#  or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
#  for more details.
#
#================================================================================

#================================================================================
#
# Theme client
#
# Set OWNTHEME to 1 if you want to theme the client. In that case put the required
# files in '/replacements/mytheme/' Read the comment for buildCustomizations() in
# the file 'library' for more information.
# example: OWNTHEME=0

#================================================================================

OWNTHEME=0



#================================================================================
#
# Windows client
#
# Enter path and file name of your certificate to code sign the windows client.
# The PFX file should contain your private key.
# example: pathCodeSignCertificate="${CUR_DIR}/certificate.pfx"
#
# Enter the url of your timestamp server.
# example: serverTimeStamp="http://timestamp.comodoca.com/authenticode"
#
# Enter the url to show in the certificate popup.
# example: infoURL="https://yourwebsite.com"
#
# Default the name of the client contains '0-setup', where 0 is the build number.
# Set CHANGENAME to 1 if you want to remove that.
# example: CHANGENAME=0
#
#================================================================================

pathCodeSignCertificate=""

serverTimeStamp=""

infoURL=""

CHANGENAME=0



#================================================================================
#
# Mac client
#
# macDeveloperIDApplication
# Leave empty if you have no Developer ID Application
# example: macDeveloperIDApplication="Developer ID Application: Name (AB123A1A11)"
# (as it apears in keychain.app)
#
# macDeveloperIDInstaller
# Leave empty if you have no Developer ID Installer
# example: macDeveloperIDInstaller="Developer ID Installer: Name (AB123A1A11)"
# (as it apears in keychain.app)
#
# Enter path and file name of your Sparkle private key; leave empty if you have none;
# in that case the client will not notify on updates.
# example: sparklePrivateKey="${CUR_DIR}/dsa_priv.pem"
#
# Enter URL for updates of the mac client; that file is called an appcast.
# example: macUpdateURL="https://updates.owncloud.com/client/" or
#          macUpdateURL="https://www.website.com/downloads/update.rss"
#
#================================================================================

macDeveloperIDApplication=""

macDeveloperIDInstaller=""

sparklePrivateKey=""

macUpdateURL=""



#================================================================================
#
# Hashcode for the version to build
#
#================================================================================

# version 1.7.0 (2014-11-06)
mirallhash="17a4299f74f4db7fc82f4b90f1e501c81288697b"