#!/bin/sh -e
# postrm script for owncloud-config-apache

# FROM http://anonscm.debian.org/cgit/pkg-owncloud/owncloud.git/plain/debian/postinst
# https://github.com/owncloud/core/issues/15038

set -e

#DEBHELPER#

if type a2disconf >/dev/null 2>/dev/null; then
  # FIXME: configure case below pulls symlinks from conf-available manually.
  a2disconf owncloud || true
  service apache2 reload || true
fi

exit 0
